# 公共配置文件
spring:
  application:
    name: zhiyixi
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # todo 取消注释开启分布式 session（须先配置 Redis）
    # store-type: redis
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zhibi?serverTimezone=UTC
    username: root
    password: 123456
  # Redis 配置
  # todo 需替换配置，然后取消注释
  redis:
    database: 0
    host: 192.168.153.128
    port: 6379
    password: aip036
    timeout: 5000
  # Elasticsearch 配置
  # todo 需替换配置，然后取消注释
#  elasticsearch:
#    uris: http://localhost:9200
#    username: root
#    password: 123456
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
server:
  address: 0.0.0.0
  port: 8101
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    #    指定日志实现类为 StdOutImpl，即标准输出实现
#    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）


# 对象存储
# todo 需替换配置
#cos:
#  client:
#    accessKey: xxx
#    secretKey: xxx
#    region: xxx
#    bucket: xxx
# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "智易析-智能BI平台接口文档"
    version: 1.0
    description: "智易析-智能BI平台接口文档"
    concat: "<a href='https://github.com/Agan-ippe'>知莫</a>    wjy7136@163.com"
#    email: "wjy7136@163.com"
    group:
      default:
        group-name: "默认分组"
        api-rule: package
        api-rule-resources:
          - com.zhiyixi.controller

# 讯飞星火大模型配置
xing-huo:
  client:
    appId: 4b2280b1
    apiKey: 0b9a6d5a06e269d2b4a4e3c92517aace
    apiSecret: MDM4OGU4YjU0YWI3YWY1ODNlYzE2NWIx
